[package]
name = "home-monitor-rs"
version = "0.1.0"
authors = ["Sascha Montellese <sascha.montellese@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.1"
exitcode = "1.1.2"
fastping-rs = "0.2.3"
log = "0.4.14"
pnet = "0.27.2"
serde = { version = "1.0.123", features = ["derive"] }
serde_json = "1.0.61"
signal-hook = "0.3.4"
simplelog = { version = "0.9.0", default-features = false }
ssh2 = "0.9.1"
wakey = "0.1.2"

[dev-dependencies]
clippy = "0.0.302"
rustfmt = "0.10.0"
