name: Rust Code Checks

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly

    steps:
      - uses: actions/checkout@v2

      - name: Setup Rust ${{ matrix.rust }}
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt, clippy

      - name: Cache for Rust ${{ matrix.rust }}
        id: cache-cargo
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ matrix.rust }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-${{ matrix.rust }}-

      - name: Build using Rust ${{ matrix.rust }}
        uses: actions-rs/cargo@v1
        if: steps.cache-cargo.outputs.cache-hit != 'true'
        with:
          command: build

      - name: Run unit tests
        uses: actions-rs/cargo@v1
        with:
          command: test

      - name: Check Rust code formatting
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Lint Rust code
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
